server:
  port: 8083

spring:
  application:
    name: micro-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    registry-fetch-interval-seconds: 1
    disable-delta: true
    service-url:
      defaultZone: http://localhost:8080/eureka/