server:
  port: 8081

spring:
  application:
    name: caller-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    disable-delta: true
    service-url:
      defaultZone: http://localhost:8080/eureka/

ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  retryableStatusCodes: 502, 503